### ISSUE TITLE
Cannot read property on linux (using broken-link-checker)

### ISSUE THREAD

**Issue by Cerberooo** [stevenvachon/urlobj#5]
```bash
[...]/node_modules/urlobj/lib/parseUrl.js:124
			if (url.search[0] === "?")
			              ^

TypeError: Cannot read property '0' of null
    at Object.parseUrl [as parse] ([...]/node_modules/urlobj/lib/parseUrl.js:124:18)

# or

/usr/lib/node_modules/broken-link-checker/node_modules/urlcache/node_modules/urlobj/lib/parseUrl.js:124
			if (url.search[0] === "?")
			              ^

TypeError: Cannot read property '0' of null
    at Object.parseUrl [as parse] (/usr/lib/node_modules/broken-link-checker/node_modules/urlcache/node_modules/urlobj/lib/parseUrl.js:124:18)
``` 

This solves it (line 122):

```javascript
if (url.search !== "" && url.search)
```

On windows everything is fine

**Comment by stevenvachon** [comment]
Fixed in v0.0.11
